### PR TITLE
Hide panels and panel toggle buttons when activating token simulation

### LINKED ISSUE #5870: Token simulation plugin is broken with v5.46.0
### Describe the bug

When I update to Desktop Modeler 5.46, the token simulation plugin fails to work.

### Steps to reproduce

1. Download the plugin and use latest version
3. now this happens

### Expected behavior

No failure

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.46.0
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: camunda-modeler-plugin-token-simulation

### Additional context

SUPPORT-32373

### PR DESCRIPTION
**Pull request by barinali**
This pull request is to supersede https://github.com/camunda/camunda-modeler-token-simulation-plugin/pull/148 as the actual fix for Camunda Modeler v5.46.0.

Along with the release incl. these changes, I think we should also update the compatibility table in the README file to indicate Camunda Modeler 5.46.0 is supported as of the next version (0.23.0).

Related to [SUPPORT-32373](https://jira.camunda.com/browse/SUPPORT-32373).
Related to camunda/camunda-modeler#5870

**Proposed Changes**

Close open side panels when activating token simulation, restore them when deactivating.

- Replace DOM-based panel hiding (`HideModelerElements`) with a client plugin (`TogglePanelsOnSimulation`) that uses the modeler's layout system to close and restore panels
- Close both the side panel (properties/test tabs) and the variables panel when simulation starts
- Restore previously open panels to their exact state (including active tab) when simulation ends
- Users can still manually toggle panels during simulation
- Rename `HideModelerElements` to `DisableSimulationOnSave` to reflect its remaining responsibility

**Breaking Changes**

- Requires Camunda Modeler >= v5.46.0 due to side panel restructuring

Closes https://github.com/camunda/camunda-modeler/issues/5870

### CODE REVIEW

**Comment by philippfromme** [comment]
What if I just reopen the panels through keyboard shortcuts?

**Comment by barinali** [comment]
> What if I just reopen the panels through keyboard shortcuts?

They will just reopen. It's currently the same in the main branch. Since `hidden` class was added to the `.properties` panel only upon activating token simulation plugin, one could have double-invoked the keyboard shortcut to toggle the panel to bring it in front.

I perceived the logic of hiding panels more like better UX to provide enough space in the modeler for the "token simulation log". So, in this revision, I did not try to hide panels permanently.

If we want to disable panels completely in a way that they cannot be open while token simulation plugin is activated, I think we'll have to cover points like;

1. disabling keyboard shortcuts
2. hiding panels
3. hiding panel toggle buttons

prior to 5.46.0, 1. was an oversight, 3. wasn't there to consider.

@philippfromme, any recommendations for the direction we may like to take?

**Comment by philippfromme** [comment]
> They will just reopen.

I think this wasn't intended. You should not be able to model when token simulation is active. That's why we (attempt to) hide all other UI elements that are used for modeling like the context pad and do some even [crazier things](https://github.com/bpmn-io/bpmn-js-token-simulation/blob/main/lib/features/disable-modeling/DisableModeling.js). Play circumvents this by being a completely separate view to begin with. Task testing is another instance of a feature that is not compatible with modeling at the same time. It cancels the test if you start modeling. I'm wondering what a proper solution would look like and whether token simulation as an inline plugin is actually a good idea to begin with. 🤔

Regardless of that we need to fix the regression. I'll review this now.

**Comment by philippfromme** [comment]
This is what I mean:

image

Modeling with token simulation actually blows up. But that was broken already. I'll open a separate issue for that.

File: client/DisableSimulationOnSave.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+export default function DisableSimulationOnSave(eventBus, toggleMode) {
```
Comment (philippfromme) [inline client/DisableSimulationOnSave.js]: What is the use case for this behavior?

**Comment by barinali** [comment]
@philippfromme thanks for the review!

I have also chatted about this pull request with @barmac in the morning huddle. What I am planning to do now;

- Remove the relatively complex logic of toggling panels programmatically
- Apply the CSS approach to hide the panels (like before) and panel toggle buttons
- Possibly disable the keyboard shortcuts for the panel toggle actions

What do you think?

File: client/DisableSimulationOnSave.js (hunk 1 above)
Comment (barinali) [reply client/DisableSimulationOnSave.js]: This is a preserved logic from `HideModelerElements`. While I took the initiative to change the product behavior* for panels, I did not want to remove an existing explicit implementation details.

\* to be improved to permanently disable them

**Comment by philippfromme** [comment]
I think the most reasonable approach for now would be to just fix what is broken without introducing more hacks like trying to disable the keyboard shortcuts without a proper way to do this.

**Comment by barmac** [comment]
+1 to hiding the modeling UI visually

**Comment by barinali** [comment]
Thanks for the remarks, @barmac @philippfromme. I have updated the approach taken with the previous one. Hid the panel toggle buttons as well, but didn't use `display: none;` as it causes layout shift there (associated with [this](https://camunda.slack.com/archives/GP70M0J6M/p1776253221893819) I think).

I kept the `.properties` in the list of elements to hide so that the fix we are performing is not a breaking change here, but backward compatible.

**Comment by barinali** [comment]
For overriding the keyboard shortcuts, I think we may cover it with something like below.

Let me know if you think it's worth it. I may create another pull request for this.

```javascript
  function suppressPanelShortcuts(event) {
    var mod = event.metaKey || event.ctrlKey;

    if (mod && event.key.toLowerCase() === 'p') {
      event.preventDefault();
      event.stopPropagation();
    }
  }

  eventBus.on(TOGGLE_MODE_EVENT, function(context) {
    var active = context.active;

    if (active) {
      document.addEventListener('keydown', suppressPanelShortcuts, true);
    } else {
      document.removeEventListener('keydown', suppressPanelShortcuts, true);
    }

    ...

  });
```

**Comment by barmac** [comment]
Not sure how it worked before the changes, but I can still open the properties panel when I switch from between the diagrams.

https://github.com/user-attachments/assets/f621d16c-3565-4926-bb07-7d3aceb44d8b

**Comment by barmac** [comment]
OK this was broken prior to the PR (checked main + 5.45), so we can also leave it for another fix.

**Comment by barmac** [comment]
Extracted to a separate issue: https://github.com/camunda/camunda-modeler-token-simulation-plugin/issues/150

**Comment by philippfromme** [comment]
> Let me know if you think it's worth it. I may create another pull request for this.

This is 💯 hacky so let's not do this. 😉

**Review by barmac — APPROVED** [review]

**Comment by barinali** [comment]
@philippfromme is this pull request clear to be merged from your POV? If so, I'd like to merge, and make a new release as v0.22.1.

**Comment by barmac** [comment]
@barinali Let's also add the version to the compatibility notice: https://github.com/camunda/camunda-modeler-token-simulation-plugin#compatibility-notice

**Comment by barinali** [comment]
> @barinali Let's also add the version to the compatibility notice: https://github.com/camunda/camunda-modeler-token-simulation-plugin#compatibility-notice

@barmac I think we do not need to update it as this revision does not introduce a breaking change. So the current compatibility table is still valid.

**Comment by barmac** [comment]
> > @barinali Let's also add the version to the compatibility notice: https://github.com/camunda/camunda-modeler-token-simulation-plugin#compatibility-notice
> 
> @barmac I think we do not need to update it as this revision does not introduce a breaking change. So the current compatibility table is still valid.

You can't use a version before this fix with >=5.46 though, right?

**Comment by philippfromme** [comment]
Works on my machine, too. Integration is not perfect, but hasn't ever been.
